name: responsive_x
description: A simple Flutter package to handle responsiveness
version: 0.0.5
homepage: https://github.com/yusubx/ResponsiveX
repository: https://github.com/yusubx/ResponsiveX

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

## dev_dependencies:
##  flutter_test:
##    sdk: flutter

